name: n8n

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      GENERIC_TIMEZONE: ${GENERIC_TIMEZONE}
      TZ: ${GENERIC_TIMEZONE}
      N8N_PROTOCOL: ${N8N_PROTOCOL}
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
      N8N_RUNNERS_ENABLED: ${N8N_RUNNERS_ENABLED}
      N8N_SSL_CERT: ${N8N_SSL_CERT}
      N8N_SSL_KEY: ${N8N_SSL_KEY}
    volumes:
      - data:/home/node/.n8n

volumes:
  data: